#
# Build for the Nonprod CI AKS Cluster
#
name: Nonprod AKS Pipeline
trigger: none
pr: none
variables:
  environment: 'nonprod'
  aksResourceGroup: 'cnp-aks-rg'
  aksClusterName: 'cnp-aks-cluster'
  keyvaultName: 'infra-vault-nonprod'
  serviceConnection: 'azurerm-nonprod'
  aksParametersFile: 'arm/parameters/aks/nonprod.json'
  helmVersion: '2.16.1'
  acrName: hmcts
  
jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: ../steps/keyvault-ci.yaml
    parameters:
      serviceConnection: $(serviceConnection)
      keyvaultName: $(keyvaultName)

- job: DeployAKS
  dependsOn: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    aksServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalId']]
    aksServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalSecret']]
  steps:
  - task: HelmInstaller@1
    displayName: 'Install Helm '
    inputs:
      helmVersionToInstall: 2.16.1

  - task: AzureCLI@1
    displayName: 'Create namespaces'
    inputs:
      azureSubscription: azurerm-nonprod
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite
        helm init --client-only

  - task: DownloadSecureFile@1
    displayName: 'Download flux deploy key'
    inputs:
      secureFile: preview-flux-git-deploy.yaml

  - task: Bash@3
    displayName: 'Create flux deploy key secret'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        kubectl -n admin delete secret flux-git-deploy
        kubectl create -f $(Agent.TempDirectory)/preview-flux-git-deploy.yaml

  - task: Bash@3
    displayName: 'Install FluxCD Flux'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        helm repo add fluxcd https://charts.fluxcd.io
        kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/chart-0.3.0/deploy/flux-helm-release-crd.yaml
        helm upgrade flux fluxcd/flux --install --namespace admin -f helm/nonprod/flux.yaml --version 0.15.0 --wait
        helm upgrade --name helm-operator fluxcd/helm-operator -f helm/nonprod/helm-operator.yaml --namespace admin --version 0.3.0 --wait



